import json
import boto3
import os

s3_client = boto3.client('s3')
dynamodb = boto3.resource('dynamodb')
Table_Name = os.environ['Table_Name']

def handler(event,context):
    """
    Read the event generated by S3.
    get s3 bucket name and object name from event.
    Read the object from s3.
    convert to dict object
    add dict item to dynamo db table.
    """
    bucket = event['Records'][0]['s3']['bucket']['name']
    json_file_name = event['Records'][0]['s3']['object']['key']

    #get object from s3
    json_boject = s3_client.get_object(Bucket=bucket,Key=json_file_name )

    #read json object
    jsonFileReader = json_boject['Body'].read()

    #Make json string to dict key value pair
    jsonDict = json.loads(jsonFileReader)
    
    #get dynamo db table 
    table = dynamodb.Table(Table_Name)

    #Add item to dynamo db table
    table.put_item(Item=jsonDict)

    return "Record Inserted Succesfully"

